// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    MinConfigProvider: typeof import('@baberat/minnie-vue/es')['MinConfigProvider']
    MinModal: typeof import('@baberat/minnie-vue/es')['MinModal']
  }
}
